[package]
name = "hello-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.2.1"

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
litesvm = "0.6.1"
solana-sdk = "2.2.1"
solana-client = "2.3.13"

[features]
custom-heap = []
custom-panic = []


